### ISSUE TITLE
Config system makes it impossible to configure port number

### ISSUE THREAD

**Issue by leonerd** [matrix-org/matrix-appservice-bridge#1]
The port number that the bridge runs as is given, somewhat bizarrely, as a construction parameter to the `Cli` object. Other construction parameters here tell it how to read the config file. It's only when you get to the `run` function that you have access to the details given in the config file, which is somewhat too late to apply a port number configured there.

This is inconvenient.

**Comment by Kegsay** [comment]
As discussed IRL a few weeks back: You can specify a `port` key on your bridge-specific configuration file and use that instead of the `port` value provided to `run()`.
