### ISSUE TITLE
Room upgrade handler should support optionally automatically moving ghosts over to the new room

### ISSUE THREAD

**Issue by turt2live** [matrix-org/matrix-appservice-bridge#102]
As per https://github.com/matrix-org/matrix-appservice-bridge/pull/100#pullrequestreview-213564336 (with surrounding context).

**Comment by Half-Shot** [comment]
I did this :)

**Comment by turt2live** [comment]
(context: I'm dumb and didn't see https://github.com/matrix-org/matrix-appservice-bridge/pull/100/commits/4254c9b42b0dcbd1b266a7d863cc17359ba4d34b happened)
