### ISSUE TITLE
[Feature Request] TypeScript Support

### ISSUE THREAD

**Issue by huan** [matrix-org/matrix-appservice-bridge#106]
It would be very helpful if we can have TypeScript typing definitions with the npm module.

And It would be fantastic if we could be able to rewrite the whole project from JS to TS. ;-)

---

#### UPDATE July 7, 2019

@Half-Shot 

I had spent around two full days to study the document and write the typings for matrix-appservice-bridge.

With the typing system, it helped me a lot to learn the API and prevent lots of potential bugs. I think it's worth to publish them, the best will be integrated into our npm module.

The typing definition is still working in progress and heavy developing, you can watch it at <https://github.com/huan/matrix-appservice-wechaty/blob/master/src/typings/matrix-appservice-bridge.d.ts>.

I'll create a pull request to add the typing to this repository after I get my project done, and any suggestion will be welcome by leaving comments under this issue.

Link to <https://github.com/huan/matrix-appservice-wechaty/issues/13>

Thanks!

**Comment by huan** [comment]
Have just sent a PR for typing for Matrix AppService Bridge (matrix-appservice-bridge) to DefinitelyTyped.

See: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42674

**Comment by huan** [comment]
The PR is merged to the DefinitelyTyped repository.

now we can use `@types/matrix-appservice-bridge` by `npm install`:

```sh
npm install @types/matrix-appservice-bridge -D
```

**Comment by Half-Shot** [comment]
Thanks for setting up some typings while we've been JS-only. We are now publishing partial types for the library and are rapidly converting most of the code to be native TS.

In the meantime, I will close this as we have a good coverage of Typescript support already.
