### ISSUE TITLE
Support E2E so we can bridge megolm rooms

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-bridge#16]

**Comment by J3m5** [comment]
Hello, I might be interested by this feature.

I'm looking for a way to add e2e encryption data and message exchange in a web application and I'm wondering if it could be possible to use a matrix server to achieve this in some way.

This would involve making a bridge between a nodejs server and the matrix server with e2e encryption.

Is that even possible?

**Comment by Half-Shot** [comment]
Closing this in favor of #231
