### ISSUE TITLE
Can't send files

### ISSUE THREAD

**Issue by qwetboy10** [matrix-org/matrix-appservice-bridge#181]
Unless I missed something, there doesn't seem to be a way to send images and other files with intents. Do I have to use sendEvent instead? I'd be willing to submit a pull request with the functionality, but I just want to be sure I'm not missing something before I add the functionality.

**Comment by Half-Shot** [comment]
This is similar to https://github.com/matrix-org/matrix-appservice-bridge/issues/56. Currently you are expected to do `intent.getClient()` and then use `https://matrix-org.github.io/matrix-js-sdk/8.0.0/module-base-apis.MatrixBaseApis.html#uploadContent` to upload the file. 

If you want to build this functionality into the Intent class, that would be much appreciated.
