### ISSUE TITLE
Perform ghost echo suppression on all user regexp patterns, not just the first one

### ISSUE THREAD

**Issue by leonerd** [matrix-org/matrix-appservice-bridge#25]
See

  https://vector.im/develop/#/room/!zOmsiVucpWbRRDjSwe:matrix.org/$147438129821098UXnET:matrix.org

  https://github.com/matrix-org/internal-config/commit/160598b99e4e15c5b92234e670cd54ea3af5e567

**Comment by Half-Shot** [comment]
I believe this works, as per `_isMatch` in `AppServiceRegistraton` in `matrix-appservice`
