### ISSUE TITLE
Add documentation on how to generate a changelog file

### ISSUE THREAD

**Issue by MadLittleMods** [matrix-org/matrix-appservice-bridge#265]
Add documentation on how to generate a changelog file.

It looks like you might need to use [`scripts/changelog-release.sh`](https://github.com/matrix-org/matrix-appservice-bridge/blob/5574b292d1b8df289782c45689095d57d393518a/scripts/changelog-release.sh) but also requires `python` and `towncrier` and is a shell script which isn't very Windows friendly.

I just created a `changelog.d/264.feature` file where the number corresponds to the PR number.

**Comment by Half-Shot** [comment]
The script is just for releases. We should have something like https://github.com/matrix-org/matrix-bifrost/blob/develop/CONTRIBUTING.md though in the repo.

**Comment by MadLittleMods** [comment]
Thanks for the link! I created a PR to add the basic same structure to this project: https://github.com/matrix-org/matrix-appservice-bridge/pull/269

**Comment by Half-Shot** [comment]
PR merged.
