### ISSUE TITLE
{Slack,Gitter} bridge refactoring hitlist

### ISSUE THREAD

**Issue by leonerd** [matrix-org/matrix-appservice-bridge#29]
This is less of a bug and more of a list of things (for my own sanity if nothing else) to extract from the current near copy-pasta mess of `matrix-appservice-{slack,gitter}` and put in the bridge library.

Entire files that can be copied (near-)verbatim
- [ ] `lib/AdminCommand.js`
- [ ] `lib/MatrixIdTemplate.js` from `matrix-appservice-gitter`
- [ ] `lib/MatrixUser.js`
- [x] `lib/Metrics.js`
- [ ] `lib/Provisioning.js`

Files that vary in implementation between Slack and Gitter but could share a common base class:
- [ ] `lib/BridgedRoom.js`
- [ ] `lib/SlackGhost.js` and `lib/GitterUser.js`

Then finally we come to the big one; all of the various parts of `lib/MatrixSlackBridge.js` and `lib/MatrixGitterBridge.js` that can be pulled out:
- [ ] automatic setup and use of `StateLookup`
- [ ] setup and delegation methods for metrics counters
- [x] automatic counting of bridge "intent" objects
- [ ] storage/metric counting/lazy construction of MatrixUser and {remote}User objects
- [ ] storage/metric counting/lazy construction of BridgedRoom instances, keyed bidirectionally
- [x] counting of Matrix client API calls
- [ ] returning a full `http` URL on the homeserver for a given `mxc`
- [ ] utility methods like `listGhostUsers`, `drainAndLeaveMatrixRoom`, `listRoomsFor`
- [ ] Matrix message routing and handling for admin room
- [ ] Checking user powerlevels for permission to execute a provisioning request

**Comment by Half-Shot** [comment]
I think we're not hitting much of this list :)
