### ISSUE TITLE
Make that lib useable with dev stack used in node js development

### ISSUE THREAD

**Issue by Inoir** [matrix-org/matrix-appservice-bridge#413]
**Is your feature request related to a problem? Please describe.**
Currently, if youre wanna use this lib, its installing [matrix-sdk-crypto-nodejs](https://github.com/matrix-org/matrix-rust-sdk-bindings). For this you need to install cargo/rustup and cmake. both is not even near of the node js dev stack.

**Describe the solution you'd like**
Dont force people to install programs they dont need!

**Describe alternatives you've considered**
Rework that lib, remove it complete.. dunno node js stack with rust is not so nice.

**Comment by turt2live** [comment]
per https://github.com/matrix-org/matrix-rust-sdk/issues/699 we're replacing the entire bindings with something that has prebuilds for common environments.
