### ISSUE TITLE
Add `intent.uploadAndSendImage`

### ISSUE THREAD

**Issue by leonerd** [matrix-org/matrix-appservice-bridge#56]
Almost all of the bridges, except IRC, support uploading images from the 3PN to Matrix. Each of these bridges copypastes the same basic code shape to upload an image to the media repo from some sort of in-memory Buffer object, obtaining the `mxc://` URL, and post that into a room as an `m.image` message.

These could be neatened up a bit with a helper method on the Intent objects themselves.

**Comment by turt2live** [comment]
Might be pushing the limits of what the appservice-bridge should be doing, but an option to also feed it a url instead of a buffer would be appreciated as well. Mostly for the networks that say "here's an image url - you deal with it".

**Comment by Half-Shot** [comment]
(I think we did this, or again the bot-sdk adds support for this)
