### ISSUE TITLE
Add `intent.downloadContent`

### ISSUE THREAD

**Issue by leonerd** [matrix-org/matrix-appservice-bridge#57]
Similar to #56, almost every bridge besides IRC can transport images from Matrix into the 3PN, and in each case has to copypaste the same lines of code to perform an HTTP(S) download from the media repo, by extracting bits of the `mxc://` URL and turning it into a regular `https://` URL for its own media repo. This could also be neatened up by putting it in the Intent object itself.

**Comment by Half-Shot** [comment]
I think we're already got this already, or at least the bot-sdk provides this.
