### ISSUE TITLE
Intent#createRoom "createAsClient" option not honored

### ISSUE THREAD

**Issue by kfatehi** [matrix-org/matrix-appservice-bridge#59]
It appears that this option https://github.com/matrix-org/matrix-appservice-bridge/blob/8f60f3e84a98d8bfd4dbd52d5403ff1c841f7d32/lib/components/intent.js#L294 being set to true still joins the AS bot to the room.

**Comment by Half-Shot** [comment]
It certainly should be by now. 

```
 */
Intent.prototype.createRoom = function(opts) {
    var self = this;
    var cli = opts.createAsClient ? this.client : this.botClient;
    var options = opts.options || {};
   ...
```
