### ISSUE TITLE
Third Party Endpoints don't check access tokens

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/matrix-appservice-bridge#76]
A homeserver is able to request third party lookup information without requiring an `access_token`.

This will break existing stuff, also a spec PR should be made first.

**Comment by Half-Shot** [comment]
There is already an auth spec for this https://matrix.org/docs/spec/application_service/r0.1.2#third-party-networks, so synapse needs to get itself sorted out.

**Comment by Half-Shot** [comment]
This was completed a while ago from our side, but needs enabling by default. For that, we need Synapse to send access tokens.
