### ISSUE TITLE
EventStore for storing eventIds against remote ids

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-appservice-bridge#92]
and any details about them. Essentially this is just like the other stores. We would also include a source key to tell us if the event came from the remote or matrix side.

Keys required are:
- Matrix Room Id
- Remote Room Id
- Matrix Event Id
- Remote Event Id
- Source
- Data (could be sender or something it we cared about senders)

**Comment by Cadair** [comment]
This should also be able to do efficient bi-directional lookups and also probably be configurable to cache on a per-room basis in case the remote service does not provide uniqueness.

**Comment by Half-Shot** [comment]
Oh good shout, yes. Let's also include which local and remote rooms they are part of.
